server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions-managed.yaml

clients:
  - url: ${GRAFANA_LOKI_PUSH_URL}
    basic_auth:
      username: ${GRAFANA_LOKI_USERNAME}
      password: ${GRAFANA_LOKI_API_KEY}

scrape_configs:
  - job_name: envault-docker-managed
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project
      - target_label: job
        replacement: envault-managed
