services:
  promtail-managed:
    image: grafana/promtail:2.9.8
    container_name: envault-promtail-managed
    command: -config.file=/etc/promtail/promtail-config.yml -config.expand-env=true
    env_file:
      - ../ops/managed-observability.local.env
    volumes:
      - ../observability/promtail-managed-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - envault-network

networks:
  envault-network:
    external: true
    name: envault-network
