services:
  loki:
    image: grafana/loki:2.9.8
    container_name: envault-loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ../observability/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    ports:
      - "127.0.0.1:3100:3100"
    restart: unless-stopped
    networks:
      - envault-network

  promtail:
    image: grafana/promtail:2.9.8
    container_name: envault-promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../observability/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - envault-network

volumes:
  loki-data:
    driver: local

networks:
  envault-network:
    external: true
    name: envault-network
